//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUANCAFFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDon
    {
        public string TenMatHang
        {
            get
            {
                return this.TenSP();
            }
        }

        public string DonViTinh
        {
            get
            {
                return this.DVT();
            }
        }
        private string TenSP()
        {
            foreach (var item in DoUong.DSDU())
            {
                if (this.IDDoUong == item.IDDoUong)
                {
                    return item.TenDoUong;
                }
            }
            return " Null";

        }

        private string DVT()
        {
            foreach (var item in DoUong.DSDU())
            {
                if (this.IDDoUong == item.IDDoUong)
                {
                    return item.DonViTinh;
                }
            }
            return "Not Name";

        }
        public double ThanhTien
        {
            get
            {
                return this.SoLuong * this.GiaBan;
            }
        }
    }
}
